print("=== Personal Profile Creator ===")
Full_name = input("What your name : ")
age  = input("How old are you : ")
email = input("What is your email : ")
phone = input("What is your phone number : ")
hobby = input("What is your favorite hobby : ")

print("== Your profile ==")
print("Name : ",Full_name)
print("Age : ",age)
print("Email : ",email)
print("Phone number : ",phone)
print("Favorite Hobby : ",hobby)